var studentInfoTemplate = `<tbody>
  <tr>
    <th>Name</th>
    <td>:name</td>
  </tr>
  <tr>
    <th>Surname</th>
    <td>:surname</td>
  </tr>
  <tr>
    <th>Age</th>
    <td>:age</td>
  </tr>
  <tr>
    <th>Birthday</th>
    <td>:birthday</td>
  </tr>
  <tr>
    <th>Gender</th>
    <td>:gender</td>
  </tr>
  <tr>
    <th>Skype</th>
    <td>:skype</td>
  </tr>
</tbody>`;